language: node_js
node_js:
- node
notifications:
  slack:
    secure: 0/lG0kalaj6X7Pt+0zr0vKTxi676V5PR430M2nMmpsnpgf7rTRZQKNjIMMIE5PP/EquHbFhcS+rf6LbJ8O5nhE4dtax96U0EQT698V24gukDor/Mrq3/F5OnGuJxVIjm4yp+goBkfOmxzTjHQaOCh5esbG3bKmA9Ywn/PBwHaqkxXLy9COk4kJXbFVnsLDJzgTQmyCL8oUZq7UOKOmFoAcRMH5dD4zHRg108rhCBg3nmDvufJ7gWEdH8J8u9uPtPjfGLMnRMYSfuxQk1QZZNyEsP3SUdKN3B6XLmaqYerhuYeCIBRWuqS4FrCg9bgvWpGoCDIZZ/vsr0Sx35YtlIiL1bc5iat/jBFh3HbXb4nyM+mxAaxJwnCj0wT3Um5V6F61vtQlySrp9uiN2jKyWEEsb2c4m/cXIMZFPOZD1zKvt6915wxnIGbKjXVRp/4jVex9SRx9N4RYu/Xii59Fxv5H1dd6zDkagiQ8xAKSK1pH24baaeVRfEpWye+4RZaEr2lCQHh9EtpDTMPpbK+chwwOEuPgCcEfDWjnhd26Mcswj0hRlzdbDV0Vz2WCdHZsy9/aP4caNekzpvWp5ubj8GdICofUqq3GfnvSLeLxw/awW2bR5F/cdVbri8BIoKC998INrljtfha1cQQ8yHp8sJrCeTobnvy/Yrx3tuH+DSunA=
